apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: internetgateways.oci.networking
spec:
  group: oci.networking
  scope: Namespaced
  names:
    plural: internetgateways
    singular: internetgateway
    kind: InternetGateway
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [region, lifecycle, vcnRef]
              properties:
                lifecycle:
                  type: object
                  required: [mode]
                  properties:
                    mode:
                      type: string
                      enum: ["Managed", "Import"]
                region:
                  type: string
                ocid:
                  type: string
                vcnRef:
                  type: object
                  properties:
                    name:
                      type: string
                enabled:
                  type: boolean
            status:
              type: object
              properties:
                ocid:
                  type: string
                lifecycleState:
                  type: string
