apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: routetables.oci.networking
spec:
  group: oci.networking
  scope: Namespaced
  names:
    plural: routetables
    singular: routetable
    kind: RouteTable
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [region, lifecycle, vcnRef]
              properties:
                lifecycle:
                  type: object
                  required: [mode]
                  properties:
                    mode:
                      type: string
                      enum: ["Managed", "Import"]
                region:
                  type: string
                ocid:
                  type: string
                vcnRef:
                  type: object
                  properties:
                    name:
                      type: string
                routes:
                  type: array
                  items:
                    type: object
                    required: [destination, target]
                    properties:
                      destination:
                        type: string
                      target:
                        type: object
                        properties:
                          internetGatewayRef:
                            type: string
                          natGatewayRef:
                            type: string
                          serviceGatewayRef:
                            type: string
            status:
              type: object
              properties:
                ocid:
                  type: string
