apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subnets.oci.networking
spec:
  group: oci.networking
  scope: Namespaced
  names:
    plural: subnets
    singular: subnet
    kind: Subnet
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [region, lifecycle]
              properties:
                lifecycle:
                  type: object
                  required: [mode]
                  properties:
                    mode:
                      type: string
                      enum: ["Managed", "Import"]
                region:
                  type: string
                ocid:
                  type: string
                vcnRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                cidrBlock:
                  type: string
                availabilityDomain:
                  type: string
                routeTableRef:
                  type: object
                  properties:
                    name:
                      type: string
                nsgRefs:
                  type: array
                  items:
                    type: string
                dnsLabel:
                  type: string
            status:
              type: object
              properties:
                ocid:
                  type: string
                lifecycleState:
                  type: string
