apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsresolvers.oci.networking
spec:
  group: oci.networking
  scope: Namespaced
  names:
    plural: dnsresolvers
    singular: dnsresolver
    kind: DNSResolver
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [region, lifecycle, vcnRef]
              properties:
                lifecycle:
                  type: object
                  required: [mode]
                  properties:
                    mode:
                      type: string
                      enum: ["Managed", "Import"]
                region:
                  type: string
                ocid:
                  type: string
                vcnRef:
                  type: object
                  properties:
                    name:
                      type: string
                ingressRules:
                  type: array
                  items:
                    type: object
                egressRules:
                  type: array
                  items:
                    type: object
            status:
              type: object
              properties:
                ocid:
                  type: string
