apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vcns.oci.networking
spec:
  group: oci.networking
  scope: Namespaced
  names:
    plural: vcns
    singular: vcn
    kind: VCN
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [region, lifecycle]
              properties:
                lifecycle:
                  type: object
                  required: [mode]
                  properties:
                    mode:
                      type: string
                      enum: ["Managed", "Import"]
                region:
                  type: string
                compartmentId:
                  type: string
                cidrBlocks:
                  type: array
                  items:
                    type: string
                dnsLabel:
                  type: string
                ocid:
                  type: string
            status:
              type: object
              properties:
                ocid:
                  type: string
                lifecycleState:
                  type: string
